config/routes.rb
Rails.application.routes.draw do
  get 'contatos/index'

  resources :contatos

  root 'contatos#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contato.rb
class Contato < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  def index
  	@contatos = Contato.all
  end

  def new
  end

  def show
    @contato = Contato.find(params[:id])
  end

  def edit
	@contato = Contato.find(params[:id])
  end
  
  def destroy
	@contato = Contato.find(params[:id])
	@contato.destroy
	 
	redirect_to contatos_path
  end

   def update
    @contato = Contato.find(params[:id])
 
    if @contato.update(contato_params)
      redirect_to contatos_path
    else
      render 'edit'
    end
  end


  def create
    @contato = Contato.new(contato_params)
 
	@contato.save
	redirect_to @contato
  end

 private
  def contato_params
    params.require(:contato).permit(:nome, :endereco, :email, :dataNascimento)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/views/contatos/edit.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="index">Agenda SECITEC</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
             <h5> <a class="nav-link" href="index">Home
                <span class="sr-only">(current)</span>
              </a></h5>
            </li>
            <li class="nav-item">
            <h5>  <%= link_to 'Adicionar Contato', new_contato_path, class: 'nav-link' %> </h5>
            </li>
          </ul>
        </div>
      </div>
    </nav>

<br/>
<br/>
<br/>

  <div class="container">

      <h1>Edit contact</h1>
       
      <%= form_with(model: @contato) do |form| %>
       
        <div class="form-group">
          <div class="field">
            <%= form.label :nome %><br>
            <%= form.text_field :nome, class: "form-control" %>
          </div>
        </div>
       
        <div class="form-group">
          <div class="field">
            <%= form.label :endereco %><br>
            <%= form.text_field :endereco, class: "form-control"  %>
         </div>
        </div>

        <div class="form-group">
          <div class="field">
            <%= form.label :email %><br>
            <%= form.text_field :email, class: "form-control" %>
         </div>
        </div>
       
       <div class="form-group">
          <div class="field">
            <%= form.label :dataNascimento %><br>
            <%= form.date_select :dataNascimento, class: "form-control" %>
          </div>
        </div>


        <p>
          <%= form.submit class: "btn btn-outline-primary" %>
        </p>
       
      <% end %>
  </div>
       
<%= link_to 'Back', contatos_path, class: "btn btn-outline-dark" %>

 <div class="py-5 bg-dark">
          <div class="container-fluid">
              <h5 class="text-center">SECITEC</h5>
          </div>
      </div>

app/views/contatos/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="index">Agenda SECITEC</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
             <h5> <a class="nav-link" href="index">Home
                <span class="sr-only">(current)</span>
              </a></h5>
            </li>
            <li class="nav-item">
            <h5>  <%= link_to 'Adicionar Contato', new_contato_path, class: 'nav-link' %> </h5>
            </li>
          </ul>
        </div>
      </div>
    </nav>

<div id="main-container" class="container-fluid">
     <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <div class="row">
	           <tr>
		         <div class="col-xs-6 col-md-4"><th>Nome</th></div>
		         <div class="col-xs-6 col-md-4"><th>Endereco</th></div>
		         <div class="col-xs-6 col-md-4"><th>E-mail</th></div>
		         <div class="col-xs-8 col-md-4"><th>Data Nascimento</th></div>
		         <div class="col-xs-6 col-md-4"><th colspan="3"></th></div>
	           </tr>
           </div>
        </thead>
        <tbody>
          <% @contatos.each do |contato| %>
           <div class="row">
            <tr>
             <div class="col-xs-6 col-md-4"> <td> <h6> <%= contato.nome %> </h6></td></div>
             <div class="col-xs-6 col-md-4"> <td> <h6><%= contato.endereco %> </h6></td></div>
             <div class="col-xs-6 col-md-4"> <td> <h6><%= contato.email %>  </h6></td></div>
             <div class="col-xs-6 col-md-4"> <td> <h6><%= contato.dataNascimento %> </h6></td></div>
             <div class="col-xs-6 col-md-4"> <td><%= link_to 'Visualizar', contato, class: "btn btn-link" %></td></div>
             <div class="col-xs-6 col-md-4"> <td><%= link_to 'Editar', edit_contato_path(contato), class: "btn btn-link" %></td></div>
             <div class="col-xs-6 col-md-4"> <td><%= link_to 'Deletar', contato, class: "btn btn-link", method: :delete, data: { confirm: 'Tem certezar que você quer deletar?' } %></td></div>

              </tr>
            </div>

          <% end %>
          </tbody>
       	 </table>
      	</div>
       </div>

      <div class="py-5 bg-dark">
          <div class="container-fluid">
              <h5 class="text-center">SECITEC</h5>
          </div>
      </div>

app/views/contatos/new.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="index">Agenda SECITEC</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
             <h5> <a class="nav-link" href="index">Home
                <span class="sr-only">(current)</span>
              </a></h5>
            </li>
            <li class="nav-item">
            <h5>  <%= link_to 'Adicionar Contato', new_contato_path, class: 'nav-link' %> </h5>
            </li>
          </ul>
        </div>
      </div>
    </nav>

<br/>
<br/>
<br/>

  <div class="container">

        <h1>Novo Contato</h1>

          <%= form_with scope: :contato,url: contatos_path, local: true do |form| %>
        <div class="form-group">
          <div class="field">
              <%= form.label :nome %>
              <%= form.text_field :nome, id: :contato_nome, class: "form-control" %>
            </div>
         </div>

         <div class="form-group">
            <div class="field">
              <%= form.label :endereco %>
              <%= form.text_field :endereco, id: :contato_endereco, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <div class="field">
              <%= form.label :email %>
              <%= form.text_field :email, id: :contato_email, class: "form-control" %>
            </div>
           </div>

         <div class="form-group">
          <div class="field">
              <%= form.label :dataNascimento %>
              <%= form.date_select :dataNascimento, id: :contato_dataNascimento, class: "form-control" %>
            </div>
          </div>

            <div class="actions">
                <%= form.submit  class: "btn btn-outline-primary" %>
            </div>
          <% end %>
      </div>



<%= link_to 'Back', contatos_path, class: "btn btn-outline-dark" %>

 <div class="py-5 bg-dark">
          <div class="container-fluid">
              <h5 class="text-center">SECITEC</h5>
          </div>
      </div>

app/views/contatos/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="index">Agenda SECITEC</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
             <h5> <a class="nav-link" href="index">Home
                <span class="sr-only">(current)</span>
              </a></h5>
            </li>
            <li class="nav-item">
            <h5>  <%= link_to 'Adicionar Contato', new_contato_path, class: 'nav-link' %> </h5>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <br/>
    <br/>
    <br/>

<p>
  <strong>Nome:</strong>
  <%= @contato.nome %>
</p>
 
<p>
  <strong>Endereco:</strong>
  <%= @contato.endereco %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= @contato.email %>
</p>

<p>
  <strong>Data Nascimento:</strong>
  <%= @contato.dataNascimento %>
</p>


<%= link_to 'Editar', edit_contato_path(@contato), class: "btn btn-outline-dark" %>
<%= link_to 'Voltar', contatos_path, class: "btn btn-outline-dark" %>

 <div class="py-5 bg-dark">
          <div class="container-fluid">
              <h5 class="text-center">SECITEC</h5>
          </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda2017</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>